### ISSUE TITLE
xskat not working after screen rotation

### ISSUE THREAD

**Issue by jetta20162** [rnauber/xskat-android#1]
xskat 1.4, after rotating the screen to landscape mode in some case xskat does not respond to touch screen input anymore, even after restart. the only workaround is to delete cache and game data. Happened on LG G4 with stock Android 6.0.

**Comment by rnauber** [comment]
Thank you for the bug report. Unfortunately, I do not have the time  to reproduce and investigate it myself, so contributions are very welcome! You can also contact the original author of xskat (I just repackaged it for fdroid), at http://www.xskat.de/android.html.
Bye,
Richard

**Comment by jetta20162** [comment]
After contacting the developer he suggested as a workaround choose "new game" from the option menu

**Comment by jmizv** [comment]
Seems not to be reproducible.
