### ISSUE TITLE
Fehler Rechnung

### ISSUE THREAD

**Issue by netzwanze** [rnauber/xskat-android#10]
Hallo,

wenn ich ohne 4  - spiel 5 auf Karo reize, sollte ich doch bis 45 gehen können? Ich hatte bis 40 gereizt, den Skat nicht angenommen, Karo ohne Buben gespielt, trotzdem habe ich das Spiel als Überreizt verloren?!

**Comment by rnauber** [comment]
Hallo @netzwanze,
sag' mal, was lag' denn eigentlich im Skat?
Denn ueberreizt haben koenntest du dich auch, wenn ein Bube im Skat liegt (obwohl du Hand spielst!)

https://www.skat-online.com/de/regeln-hilfe/regelwerk/internationale-skatordnung.html#K5.4.2

Schoene Gruesse,
Richard

**Comment by netzwanze** [comment]
Guten Morgen Richard,

der Bube müsste dann im Skat gelegen  haben, da nur 3 Buben von dem "Gegenüber" gespielt wurden.
Also zählt der im Skat, den ich nicht sehen konnte, auch?

Grüße Jörg

**Comment by rnauber** [comment]
> Guten Morgen Richard,
> 
> der Bube müsste dann im Skat gelegen haben, da nur 3 Buben von dem "Gegenüber" gespielt wurden.
> Also zählt der im Skat, den ich nicht sehen konnte, auch?

Genau, so interpretiere ich zumindest die Regel 5.4.2:

https://www.skat-online.com/de/regeln-hilfe/regelwerk/internationale-skatordnung.html#K5.4.2

Na dann noch viel Spass und gutes Blatt,
Richard

> Grüße Jörg

**Comment by netzwanze** [comment]
Besten Dank und eine angenehme Woche.

Danke für den genialen Zeitvertreib.
