### ISSUE TITLE
Animation speed resets after closing of app

### ISSUE THREAD

**Issue by openpaul** [rnauber/xskat-android#22]
Observed behaviour: If Animation speed is reduced it will be reset to highest speed after closing and reopening the app.

Expected behaviour: Animation speed setting should be persistent across launches as are all the other settings.

Affected version: 1.5 Android. The issue was not there in version 1.4 

Thanks for this amazing app.

**Comment by jmizv** [comment]
> Observed behaviour: If Animation speed is reduced it will be reset to highest speed after closing and reopening the app.
> 
> Expected behaviour: Animation speed setting should be persistent across launches as are all the other settings.
> 
> Affected version: 1.5 Android. The issue was not there in version 1.4 
> 
> Thanks for this amazing app. 
> 
> 
> 

I could observe that the player strength is reset now, too. Can you confirm?

**Comment by openpaul** [comment]
You are right. But only from:

++ stays ++
+ stays +
0 turns to --
- stays -
-- turns to 0

Thats an amazing bug. So maybe they are connected. Seems like there is some naming issues maybe.

**Comment by rnauber** [comment]
> You are right. But only from:
> 
> ```
> ++ stays ++
> + stays +
> 0 turns to --
> - stays -
> -- turns to 0
> ```
> 
> Thats an amazing bug. So maybe they are connected. Seems like there is some naming issues maybe.

Hm, I could not reproduce this bug. Could you please open a separate issue with a detailed description when this happens? Thank you!

**Comment by jmizv** [comment]
> 
> 
> > You are right. But only from:
> > ```
> > ++ stays ++
> > + stays +
> > 0 turns to --
> > - stays -
> > -- turns to 0
> > ```
> > 
> > 
> > Thats an amazing bug. So maybe they are connected. Seems like there is some naming issues maybe.
> 
> Hm, I could not reproduce this bug. Could you please open a separate issue with a detailed description when this happens? Thank you!

I could reproduce it and have it solved with #24
