### ISSUE TITLE
1.5 regressions

### ISSUE THREAD

**Issue by mirabilos** [rnauber/xskat-android#23]
Besides #22 the animation speed is much higher than in 1.4 even at `-` level.

It also no longer pre-selects the most likely game colour/type, and it’s possible to continue to a game without choosing the type, leading to me playing a game I don’t even know.

I’ll definitely downgrade to 1.4 now.

**Comment by toabr** [comment]
The default game is Grand, but not selected.
It would be nice to have the old behavior back.

**Comment by jmizv** [comment]
Hi @mirabilos, @toabr
I will check this, thanks for flagging out.

**Comment by rnauber** [comment]
Sorry, I can not reproduce this. Which version of the repository are you using?

**Comment by mirabilos** [comment]
rnauber dixit:

>Sorry, I can not reproduce this. Which version of the repository are you using?

I don’t understand the question. I installed this from F-Droid.

**Comment by qaws** [comment]
Sorry, wrong issue 🙃...

**Comment by jmizv** [comment]
> Sorry, I can not reproduce this. Which version of the repository are you using?

I've seen this a couple of times. It does not happy every time but I haven't found an pattern for this, neither.

**Comment by rnauber** [comment]
Sorry for the total confusion! 

> Sorry, I can not reproduce this. Which version of the repository are you using?
This comment was meant for another repository. 

> Sorry, wrong issue upside_down_face...
And this was me, logged in with my ancient account, telling you to disregard my comment...

So please completely ignore my comments, sorry again!

**Comment by mirabilos** [comment]
Animation speed is still an issue…

**Comment by jmizv** [comment]
Hi @mirabilos
I've pushed a change. Don't know if you could somehow check if this works for you? In that case we could make a new version ...

**Comment by mirabilos** [comment]
I wouldn’t know how at the moment. But even the slowest setting in 1.5 (manually chosen) is faster than 1.4, so…
