### ISSUE TITLE
[FR]: Multi-User-Support by linking two or three Devices (i.e. Instances of XSkat)

### ISSUE THREAD

**Issue by just-Nob** [rnauber/xskat-android#30]
XSkat is nice if you're alone and want to play Skat.

But wouldn't it be wonderful to have the possibility to link two XSkat instances (running on two different devices) via Bluetooth or (ad-hoc-)Wifi connection to play with two human players and one computer player?
Or just to link three devices, to have a Skat match with three human players, currently having no physical card game available?
;-)

I'ld like to add that feature by myself, but unfortunately I currently have neither the programming skills, not the time to dive into Java programming. :-(

**Comment by jmizv** [comment]
It would be wonderful to have this but I don't think anyone will ever have the time and other resource to implement this into XSkat. I'm convinced XSkat will be forever single-player as the original author mentioned on the [xskat.de](http://xskat.de) page.

Meanwhile you can check out JSkat: https://github.com/b0n541/jskat-multimodule
They plan to have it as a mobile game, too, IIRC. And there is also the possibility to connect to public available Skat servers.

**Comment by just-Nob** [comment]
Thanks for the hint.
