### ISSUE TITLE
Unintuitive representation of card distribution after dealing

### ISSUE THREAD

**Issue by StanNest** [rnauber/xskat-android#32]
Hi,

I noted that the representation of the card distribution after dealing does not seem intuitive, please see the example attached. You will note that two cards are missing: "Herz 9" and "Karo D" whereas "Pik 7" and "Kreuz 8" are found twice. Thus this is not accurately reflecting the situation after dealing. I understand that there is value to see which cards the player chose to keep, but this has been bothering me when checking "what would have happened if..." e.g. someone else had been the highest bidder with another game chosen.

Stan

![XSkat](https://user-images.githubusercontent.com/85558604/121178960-a2d7fb80-c84e-11eb-9365-75f932b8966f.jpg)

**Comment by jmizv** [comment]
Hi @StanNest 
you're right, this statistic view needs definitely some love.

**Comment by jmizv** [comment]
Hi @StanNest 
I've managed to change the statistic:

https://user-images.githubusercontent.com/37914724/214283047-ecbd0c8f-ed52-4bf1-8a2d-c5509b3d35af.png

**Comment by StanNest** [comment]
Hi,

saw your update. Great. Thanks! I do not see the latest version in the F-Droid store yet? In fact, I don't see skat or Xskat there at all right now. But I guess sooner or later I will be able to grab the new version.

Thanks, it's a lot of fun to play Xskat, especially as it does not require a data connection.

Best
Stan


28 July 2021, 21:02 from ***@***.***:

**Comment by rnauber** [comment]
> Hi, saw your update. Great. Thanks! I do not see the latest version in the F-Droid store yet? In fact, I don't see skat or Xskat there at all right now. But I guess sooner or later I will be able to grab the new version. Thanks, it's a lot of fun to play Xskat, especially as it does not require a data connection. Best Stan 28 July 2021, 21:02 f


Hi @StanNest,
unfortunately Xskat was kicked out of FDroid because of its exotic licence (#39). The simplest way to get the apk is to download it from the github release page.

Best,
Richard

**Comment by StanNest** [comment]
Hi Richard, 
thanks. Is the 516kB file xskat-debug.apk the apk I need?
And, the link "... get an .apk from here" does not exist due to a typo: "lastest" instead of "latest".
CheersStan
***@***.***:

Hi, saw your update. Great. Thanks! I do not see the latest version in the F-Droid store yet? In fact, I don't see skat or Xskat there at all right now. But I guess sooner or later I will be able to grab the new version. Thanks, it's a lot of fun to play Xskat, especially as it does not require a data connection. Best Stan 28 July 2021, 21:02 f
Hi @StanNest,unfortunately Xskat was kicked out of FDroid because of its exotic licence (#39). The simplest way to get the apk is to download it from the github release page.
Best,Richard
