### ISSUE TITLE
Jack not played in grand game

### ISSUE THREAD

**Issue by ingenerd** [rnauber/xskat-android#33]
This sounds like a user mistake, but I am absolutely sure, it is not. In a grand hand game, I played out one of my three Jacks. The opponents did not play the last Jack. Later on, Androido played a Jack. That really should not be!

**Comment by rnauber** [comment]
Thanks @ingenerd for reporting this. That sounds like a huge bug to me, but in order to fix this we would need to reproduce it first. Do you happen to have the games log (which cards were played) available?

Best,
Richard

**Comment by jmizv** [comment]
That's bad. For such cases it would be great if we could choose the cards to play with beforehand instead of letting them been drawn randomly. Some kind of game id is an idea I carry for long with me. Though no time.

**Comment by jmizv** [comment]
A friend of mine played this morning Grand Hand:

![photo_2021-07-15 10 28 10](https://user-images.githubusercontent.com/37914724/125755835-3320cc7c-ceca-4195-9cc1-53e1e3367b5c.jpeg)

In this constellation the missing Jack was played.

@ingenerd if you encounter this problem again please make sure to provide a screenshot of the game result page like above. Thanks.

**Comment by jmizv** [comment]
I would close for now as it seems not reproducable.
