### ISSUE TITLE
Wrong score count with Grand + Ouvert + Schneider 

### ISSUE THREAD

**Issue by autodidact1958** [rnauber/xskat-android#37]
**What I did:** 
I had a set of cards with 4 jacks (Bauern), 5 spades (Pik) and a diamond dame. 
The bid went to 44.
Selecting the game I chose Grand, Ouvert, Schneider

During the play I got 106 points (Schneider, but NOT Schwarz). (with -528 points)

**What did I get:** 
System rated the a game as "LOST" ! - Results of game IS NOT SCHWARZ.

**What I expected:** 
Play WON.

I replayed the game several times. In all cases the system rated the play as LOST due to SCHWARZ rule.

**Comment by jmizv** [comment]
Hi @autodidact1958 

playing a Grand Ouvert always implies that you play Schwarz. Same goes for every other Farbspiel that you are playing ouvert. Probably this is a UX related problem.

**Comment by autodidact1958** [comment]
Hi,

most likely the Problem sits behindert the cards. This rule I did not know until now. Thanks for the lesson!

Plesse close this bug message.

Yours sincerely

10.01.2022 22:19:51 Alex ***@***.***>:

**Comment by jmizv** [comment]
No problem. Thanks for playing XSkat :)
