### ISSUE TITLE
F-Droid - removal since not-FOSS licensed

### ISSUE THREAD

**Issue by licaon-kter** [rnauber/xskat-android#39]
fyi: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11515

Ref: https://spdx.org/licenses/

**Comment by the-rene** [comment]
Is there any other source for recent builds from this project? I could only find the 1.4 Version from xskat.de

**Comment by rnauber** [comment]
> Is there any other source for recent builds from this project? I could only find the 1.4 Version from xskat.de

No, I do not know any others sources. Version 1.4 at http://www.xskat.de/android.html is the base for this repository.

**Comment by rnauber** [comment]
> fyi: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11515
> 
> Ref: https://spdx.org/licenses/

I asked the original author, Gunter Gerhardt, about possible a relicensing of his code, but he did not answer yet. 
If fdroid drops xskat then the only distribution channel that is left for this version would be via github downloads.

**Comment by rms-joe** [comment]
does one of those help?

https://salsa.debian.org/debian/xskat
https://software.opensuse.org/package/xskat
https://aur.archlinux.org/packages/xskat
https://launchpad.net/ubuntu/+source/xskat
https://github.com/mfrasca/xskat

**Comment by tuxayo** [comment]
Still that license looks ok for Debian and Fedora.

https://fedoraproject.org/wiki/Licensing/XSkat_License

https://salsa.debian.org/debian/xskat
