### ISSUE TITLE
Any further development?

### ISSUE THREAD

**Issue by jmizv** [rnauber/xskat-android#4]
Hi,
are there any plans to start further development? It's a really nice app, not bloated with any useless functions and even better: no ads. Although the code works well, it could need a bit of refactoring. Will such changes even get back to the FDroid store?

I can imagine to have better statistics, like seeing the complete history of games since the last reset.

**Comment by rnauber** [comment]
Hi @jmizv,
>are there any plans to start further development? 

I am not the original author of the code, that is [Gunter Gerhardt](http://www.xskat.de/). You may want to ask him, if he is planning further development.

> Although the code works well, it could need a bit of refactoring. 

Yes, I think that is necessary.

> Will such changes even get back to the FDroid store?

I would happily merge PR that improve the code and add features! 

> I can imagine to have better statistics, like seeing the complete history of games since the last reset.

That sounds good, I am looking forward to your PRs!

**Comment by jmizv** [comment]
Hi @rnauber,
I'd really like to contribute but I need to take some time which is quite rare for the moment ;)
Thanks!
